packages:
  - apps/*
  - packages/*

catalog:
  "@biomejs/biome": ^2.3.10
  es-toolkit: ^1.43.0
  lucide-react-native: ^0.562.0
  nativewind: 4.2.1
  react-native-css-interop: ^0.2.1
  react-native-svg: ^15.15.1
  tailwindcss: 3.4.19
  typescript: ^5.9.3
  type-fest: ^5.3.1
  zod: ^4.2.1
