packages:
  - apps/*
  - packages/*

catalog:
  "@biomejs/biome": ^1.9.4
  lucide-react-native: "^0.456.0"
  nativewind: 4.1.21
  tailwindcss: ^3.4.14
  typescript: ~5.3.3
  type-fest: ^4.26.1

catalogs:
  react18:
    react: 18.2.0
    react-dom: 18.2.0
    "@types/react": ^18.2.79
