packages:
  - apps/*
  - packages/*

catalog:
  '@biomejs/biome': ^2.2.5
  es-toolkit: ^1.40.0
  lucide-react-native: ^0.525.0
  nativewind: ^4.1.23
  react-native-css-interop: 0.1.22
  react-native-svg: ^15.12.0
  tailwindcss: 3.4.18
  typescript: ^5.8.3
  type-fest: ^5.0.1
  zod: ^4.1.12
