export const LOCATION_MIN_RECORDING_INTERVAL_HOURS = 1;

export const LOCATION_DISTANCE_INTERVAL_METERS = 300;
export const LOCATION_TIME_INTERVAL_MS = 60 * 60 * 1000;

export const LOCATION_DEFERRED_UPDATES_INTERVAL_MS = 10 * 60 * 1000;
export const LOCATION_DEFERRED_DISTANCE_METERS = 500;

export const LOCATION_SHOWS_BACKGROUND_INDICATOR = false;
export const LOCATION_PAUSES_UPDATES_AUTOMATICALLY = true;
