export const ALPHA3_TO_ALPHA2: Record<string, string> = {
  USA: "US",
  GBR: "GB",
  RUS: "RU",
  CHN: "CN",
  AUS: "AU",
  KOR: "KR",
  PRK: "KP",
  DEU: "DE",
  FRA: "FR",
  ITA: "IT",
  ESP: "ES",
  CAN: "CA",
  MEX: "MX",
  JPN: "JP",
  IND: "IN",
  BRA: "BR",
  ARG: "AR",
  ZAF: "ZA",
};
